server:
  port: 1000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:1000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
      routes:
        - id: customer service
          uri: ${CUSTOMER_SERVICE_URI}
          predicates:
            - Path=/customer/**
            - Header=customer,true
          filters:
            - AddRequestHeader=customerKey, customerValue
            - AddResponseHeader=customerKey, customerValue
        - id: product service
          uri: ${PRODUCT_SERVICE_URI}
          predicates:
            - Path=/product/**
            - Header=product,true
          filters:
            - AddRequestHeader=productKey, productValue
            - AddResponseHeader=productKey, productValue
